### ISSUE TITLE
[Bug]: Posts titles are not escaped

### ISSUE THREAD

**Issue by maxirosson** [gautamkrishnar/blog-post-workflow#101]
**Describe the bug**
When generating the title with special characters (like `|`), the readme is broken when deployed to Github Pages 

For example
`- [This is an example | with an especial char](https://www.youtube.com/watch?v=Du6AdFUjy1A)
`

**Expected behavior**
Escape special characters when editing the readme: `|` -> `\|`

**Comment by gautamkrishnar** [comment]
@maxirosson its ok. 'item_exec' argument was intended to serve this purpose.
