### ISSUE TITLE
Need to import feed from Strapi CMS to github readme

### ISSUE THREAD

**Issue by Aravin** [gautamkrishnar/blog-post-workflow#107]
Hi Team,

Can you please introduce the feature to import feed using strapi cms to github

This is my website: https://www.aravin.net

This is my strapi endpoint: https://aravin-net-cms.herokuapp.com/

This is my article endpoint: https://aravin-net-cms.herokuapp.com/articles

This is my failing github actions: https://github.com/Aravin/Aravin/actions/runs/1460565385

**Comment by gautamkrishnar** [comment]
@Aravin This project supports only RSS Feeds. Not JSON Data. Please add the necessary code to convert your strapi JSON API to RSS. Just consume that API in some of the static site generators like Gatsby to create your own RSS feed.  Adding support for parsing JSON data is beyond the scope of this project.

**Comment by gautamkrishnar** [comment]
@Aravin check https://strapi.io/blog/building-a-static-website-using-gatsby-and-strapi and https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-an-rss-feed/

**Comment by Aravin** [comment]
I know how to consume strapi API @gautamkrishnar 

Thanks.
