### ISSUE TITLE
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported.

### ISSUE THREAD

**Issue by TGTGamer** [gautamkrishnar/blog-post-workflow#11]
```cmd
##[error] 	https://stackoverflow.com/feeds/user/358909 runner failed, please verify the configuration. Error:
##[error]TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
Writing to ./README.md
```

[log](https://github.com/TGTGamer/TGTGamer/runs/938432050?check_suite_focus=true#step:3:13)

**Comment by gautamkrishnar** [comment]
Looks like the URL is wrong: https://stackoverflow.com/feeds/user/358909, its not returning the feed

**Comment by gautamkrishnar** [comment]
also, @TGTGamer don't put space between the URLs: https://github.com/TGTGamer/TGTGamer/blob/master/.github/workflows/blog.yml#L17

**Comment by gautamkrishnar** [comment]
I had also added some code to prevent this in the future, so the latest version will automatically even if you don't do any changes on your end.
