### ISSUE TITLE
[New Source]: Podcasts / Multiple Platforms

### ISSUE THREAD

**Issue by thecoffeehog** [gautamkrishnar/blog-post-workflow#12]
Source Name: Anchor
Source URL: https://anchor.fm/laii
Comments: 

Podcasts are available on multiple platforms such as Google Podcasts/Spotify/Apple Podcasts etc. and Anchor distributes them to multiple platforms and also provides a link to all of them on the podcast's Anchor page.

We could fetch the links from any of the popular podcasting platforms or maybe from Anchor.fm itself, whatever is quicker to begin with.

**Comment by gautamkrishnar** [comment]
@thecoffeehog are you interested in opening a PR to add this

**Comment by gautamkrishnar** [comment]
@thecoffeehog thanks a lot for sharing.
