### ISSUE TITLE
[Bug]: Workflow failed when I add my wordpress blog feed

### ISSUE THREAD

**Issue by FranzKafkaYu** [gautamkrishnar/blog-post-workflow#125]
**Describe the bug**
I replaced the url with my own blog feed,but the work flow alaways failed,and I got this error info as blow:
![image](https://user-images.githubusercontent.com/38254177/159280889-b127c53b-9d45-4ef6-a2fe-055b6947c3cf.png)
 
And when I check my url in browser,it works 

**Expected behavior**
Workflow can run successfully.

**Screenshots**
Here is my error info:
![image](https://user-images.githubusercontent.com/38254177/159281208-176e2da4-fc48-4674-a2e0-c8ee4a68a4d2.png)

Here is a screenshot of my feed url working in browser:
![image](https://user-images.githubusercontent.com/38254177/159281481-16616d8b-3b5f-47e4-9205-9da9e2a37a7e.png)

**Workflow Yml Used**

name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://coderfan.net/category/operating-system/feed"
          disable_item_validation: true

**Additional context**

**Comment by gautamkrishnar** [comment]
@FranzKafkaYu as you can see from the above message, your website itself is returning 503 when you fetch it from github runners. If you use Cloudflare add a whitelist to fix it.

**Comment by FranzKafkaYu** [comment]
> @FranzKafkaYu as you can see from the above message, your website itself is returning 503 when you fetch it from github runners. If you use Cloudflare add a whitelist to fix it. Unfortunately, there is nothing from the project side that can be done to fix this issue.

Thank U sir.I am not familiar with these network knowledges and I will look into this. Again, thanks for your kindly help.
