### ISSUE TITLE
Could you release major version(s) of your GitHub action?

### ISSUE THREAD

**Issue by jmfayard** [gautamkrishnar/blog-post-workflow#147]
Bonjour! 🇫🇷

I contribute to [GitHub Actions Kotlin DSL](https://github.com/krzema12/github-actions-kotlin-dsl) which provides an alternative to write GitHub Actions not in YAML but in a type-safe programming language: Kotlin.

To this end we provide type-safe wrappers for currently [72 (and counting) wrapper actions](https://krzema12.github.io/github-actions-kotlin-dsl/supported-actions/). Those type-safe wrappers are generated from its `action.yml` which we update when it goes to a new major version, for example `actions/cache@v2` to `actions/cache@v3`

And of course we support your action as well!

Unfortunately when an action don't have a major version, which is what GitHub recommands, we are forced to update manually for every minor version, like from `appleboy/scp-action/v0.1.2` to `appleboy/scp-action/v0.1.3` 

See [our issue here](https://github.com/krzema12/github-actions-kotlin-dsl/issues/289)

Would you consider creating a major version for your action?
That would make our life easier, and the life of your users easier in general.

You can find here the recommendations from GitHub:

[https://github.com/actions/toolkit/blob/main/docs/action-versioning.md](https://github.com/actions/toolkit/blob/main/docs/action-versioning.md) 
(see *Recommendations* in particular)

**Comment by gautamkrishnar** [comment]
@jmfayard Thanks for reaching out. Unfortunately, Having a seprate set of versioning is not possible for this project right now. I dont think that anyone is going to use this action on production servers so type safety is not at all a problem. All the best for your project.

**Comment by jmfayard** [comment]
Hello, I'm not sure I understood your respond.
What I meant is that you currently have a release like `gautamkrishnar/blog-post-workflow@v1.7.0`
If you could create a release `v1` on GitHub, 
then your users could use ``gautamkrishnar/blog-post-workflow@v1` in their workflow and get automatically the minor release without depending on `@master` which is not reliable.

**Comment by gautamkrishnar** [comment]
@jmfayard for that to happen i need to follow the `v` prefixed release names right? Right now this project follows versioning with just numbers, not with a `v` prefix.

**Comment by jmfayard** [comment]
@gautamkrishnar 
I was not sure to be honest, but from what I understand from https://github.com/actions/toolkit/blob/main/docs/action-versioning.md#recommendations you do that simply by having a tag `v1`

```
git tag -fa v1 -m "Update v1 tag"
git push origin v1 --force
```

**Comment by gautamkrishnar** [comment]
@jmfayard thanks for explaining. I will give it a try.

**Comment by gautamkrishnar** [comment]
@jmfayard v1 tag is currently available. Thanks for the suggestion.

**Comment by jmfayard** [comment]
It worked, thanks :)
