### ISSUE TITLE
[Feature]: Conditional statement for blogs / remove duplicates

### ISSUE THREAD

**Issue by avipars** [gautamkrishnar/blog-post-workflow#157]
Occasionally, I guest post or re-share the article on two separate sources, is there a way to either have some conditional statement inside your action or a setting to ignore duplicate posts based on title?

**Comment by gautamkrishnar** [comment]
@avipars just use it 2 times eg: https://www.youtube.com/watch?v=ECuqb5Tv9qI&t=272s
