### ISSUE TITLE
Failed to fetch medium posts!

### ISSUE THREAD

**Issue by antra0497** [gautamkrishnar/blog-post-workflow#170]
### Discussed in https://github.com/gautamkrishnar/blog-post-workflow/discussions/169

<div type='discussions-op-text'>

<sup>Originally posted by **antra0497** September 16, 2022</sup>
Hi,

I am trying to fetch my medium post using a cron job, but it is failing all the time, similar is the case with WordPress blog.
Wanted to see if there is a workaround for this or if anyone has successfully done it.

![image](https://user-images.githubusercontent.com/25953832/190656249-6c3c6499-ae22-4415-8786-0ab834f307d3.png)
</div>

**Comment by gautamkrishnar** [comment]
@antra0497 please use the correct feed url, it is `https://medium.com/@antratripathi_at/feed` not the one you provided.
