### ISSUE TITLE
[Bug]: error nsddd.top/rss.xml

### ISSUE THREAD

**Issue by 3293172751** [gautamkrishnar/blog-post-workflow#174]
![SHDYK}@DDWK(P%DV 117U`T](https://user-images.githubusercontent.com/86140903/196038247-1e7d81dd-8317-4036-bd02-2bfda95f67e0.png)
Hello, I would like to ask why my subscription address is accessible, but it keeps getting errors 
[https://nsddd.top/rss.xml](https://nsddd.top/rss.xml)
![image](https://user-images.githubusercontent.com/86140903/196038320-d38ea064-5b3e-4441-b0f2-c776e620a76e.png)

**Comment by gautamkrishnar** [comment]
@3293172751 please fix the url. You are using http in your workflow instead of https
