### ISSUE TITLE
[Feature]: Support for .adoc files

### ISSUE THREAD

**Issue by hacker-DOM** [gautamkrishnar/blog-post-workflow#177]
It would be great if this tool works with non-md files, e.g. asciidoc. I guess the logic could only be modified slightly:

1. (optional) look for the precise tag (`BLOG-POST-LIST:START`) instead of including the comments
2. delete the whole line to catch comments in other languages (e.g. `// asciidoc`)

Cool tool!

**Comment by gautamkrishnar** [comment]
Hi @FabianGosebrink since this is not a common use case, I am not planning to support this in the upstream repo. Feel free to fork the repo and make the changes to satisfy your use case with asciidoc. It's not a minor change since the asccidoctor does not use a syntax similar to the markdown.
