### ISSUE TITLE
[Bug]: Response 406 when asking for rss stream

### ISSUE THREAD

**Issue by FabianGosebrink** [gautamkrishnar/blog-post-workflow#19]
**Describe the bug**
When I use the provided configuration and the cronjob runs I get a `406 Not Acceptable` response in the github action as an error.

**To Reproduce**
1. Implement Github Action as described
2. Let the job run with `feed_list: "https://offeringsolutions.azurewebsites.net/index.xml"` or `"https://offering.solutions/index.xml"`
3. See the 406 Error

```
Run gautamkrishnar/blog-post-workflow@master
  with:
    feed_list: https://offeringsolutions.azurewebsites.net/index.xml
    gh_token: ***
    readme_path: ./README.md
    max_post_count: 5
    disable_sort: false
    filter_comments: medium,stackoverflow/Comment by $author/,stackexchange/Comment by $author/
    template: default
    commit_message: Updated with the latest blog posts
    committer_username: blog-post-bot
    committer_email: blog-post-bot@example.com
##[error]https://offeringsolutions.azurewebsites.net/index.xml runner failed, please verify the configuration. Error:
##[error]Error: Status code 406
0 blog posts fetched
```

**Expected behavior**
I would hav eexpected to read the xml and show the latest blogposts.

**Screenshots**
None

**Additional context**
`"https://offering.solutions/index.xml"` is running behind cloudflare, `"https://offeringsolutions.azurewebsites.net/index.xml"` is not, both of them return a 406

**Comment by gautamkrishnar** [comment]
@FabianGosebrink try using the workflow with the newly added `user_agent` option. Set it to a google bot's user agent string and try again.

**Comment by FabianGosebrink** [comment]
Hey thanks for your quick reply and the provided help!

Unfortunately I had no no success setting the user_agent 😢

Tried it with 

`user_agent: "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"`
and
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko)`

**Comment by gautamkrishnar** [comment]
@FabianGosebrink this should be fixed on the server-side then, please check your website's code.

**Comment by FabianGosebrink** [comment]
As the error describes a `406 Error – Not Acceptable`: What content-type is the action expecting? The server returns `text/xml` which is obviously not what the github action sends as accept header. What `accept-header` is the action sending? Maybe making it configurable solves the issue? I dont know but maybe it is worth a try?

**Comment by gautamkrishnar** [comment]
The header is  'Accept': 'application/rss+xml'. Let me try adding an option to customize it.

**Comment by FabianGosebrink** [comment]
Doing a PR currently :) Want to have a look?

**Comment by FabianGosebrink** [comment]
Maybe this is worth a try...

**Comment by FabianGosebrink** [comment]
Worked locally when setting both properties: 

```
...
user_agent: "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)"
accept: "text/xml"
```

**Comment by gautamkrishnar** [comment]
@FabianGosebrink its now released can you please try using `accept_header`:`text/xml`

**Comment by FabianGosebrink** [comment]
Works perfectly now! https://github.com/FabianGosebrink/FabianGosebrink

Thank you very much!
