### ISSUE TITLE
[Feature]: Allow ignoring the commit step 

### ISSUE THREAD

**Issue by ansidev** [gautamkrishnar/blog-post-workflow#197]
**Is your feature request related to a problem? Please describe.**
I want to commit files using another GitHub Actions.

**Describe the solution you'd like**
Add options to allow ignoring the commit step.

**Comment by gautamkrishnar** [comment]
Thanks for the suggestion @ansidev this is a good feature to have, adding a new option named as `skip_commit` would be a way to go. Will work on this when I have time if no one else is there to fix this.

**Comment by gautamkrishnar** [comment]
@ansidev this is now released, you can use `skip_commit: true` to skip the committing feature.
