### ISSUE TITLE
[Feature]: Add more debug messages

### ISSUE THREAD

**Issue by ansidev** [gautamkrishnar/blog-post-workflow#198]
**Is your feature request related to a problem? Please describe.**
Currently, I am experiencing a failed job without meaningful messages.

https://github.com/ansidev/ansidev/actions/runs/4289879505/jobs/7473337976

**Describe the solution you'd like**
Add more meaningful messages to help debug easily.

**Additional context**

This workflow work: https://github.com/ansidev/ansidev/actions/runs/4288246462

I am trying to combine two workflows to reduce the number of commits since the only file which is updated is README.md.

However, your action doesn't work as I expected, and the return message is vague and does not help me to understand what was wrong.

**Comment by gautamkrishnar** [comment]
@ansidev please follow the steps mentioned here: https://github.com/gautamkrishnar/blog-post-workflow#faqs-and-common-issues
