### ISSUE TITLE
[Feature]: Ability to show github gists in Profile Readme

### ISSUE THREAD

**Issue by nasreekar** [gautamkrishnar/blog-post-workflow#21]
Just wanted to check if there is a way to write a cron job to show all the `your gists` section in the profile readme?

**Comment by gautamkrishnar** [comment]
As of now, GitHub gists don't have rss format API that we can hook into to get the posts. Implementing this via github API is beyond the scope of this project.

**Comment by gautamkrishnar** [comment]
Btw this looks like a good idea, I will work on this during my free time as a separate project, Will let you know when the MVP is ready 😄

**Comment by nasreekar** [comment]
@gautamkrishnar  I understand. Thanks for sharing your views.
And looking forward to it :)
