### ISSUE TITLE
remote: Permission to username/username.git denied to github-actions[bot].

### ISSUE THREAD

**Issue by igokhul** [gautamkrishnar/blog-post-workflow#218]
I've just added this blog post workflow. Everything seems to work fine but my .git is denied access. How could I resolve it?
![Screenshot from 2023-05-17 20-28-53](https://github.com/gautamkrishnar/blog-post-workflow/assets/84320534/0fb73980-d84d-4172-b154-6be02664ca50)

**Comment by gautamkrishnar** [comment]
@igokhul please try https://github.com/gautamkrishnar/blog-post-workflow#faqs-and-common-issues
