### ISSUE TITLE
403 error from Netlify hosted feeds

### ISSUE THREAD

**Issue by davidsneighbour** [gautamkrishnar/blog-post-workflow#238]
This issue is the same as described in #113, this time at Netlify. The workaround is identical, using an RSS proxy service. The one mentioned in #113, rssmix.com, is not working anymore. I used https://rssproxy.migor.org/. I sent a note to the team at Netlify, but I don't expect them to be too accommodating, as it's on the free tier. 

[Issue report on the Netlify community forum](https://answers.netlify.com/t/loading-rss-feed-via-github-results-in-a-403-error/109625)

**Comment by gautamkrishnar** [comment]
You may need to whitelist the GItHub IPs (https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses) addresses on Netlify. We can't do anything to fix this issue. Please contact netlfy support team to fix this issue.
