### ISSUE TITLE
[Bug]: Node.js 16 out of date.

### ISSUE THREAD

**Issue by tct123** [gautamkrishnar/blog-post-workflow#242]
When i run this workflow it says:
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: gautamkrishnar/blog-post-workflow@master. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`
It also does not refresh my blogposts in my Readme.md file.
What am I doing wrong and how can this be fixed?

**Comment by gautamkrishnar** [comment]
It is not coming from this workflow, it is coming from the checkout workflow.  Use the latest example from readme:

https://github.com/gautamkrishnar/blog-post-workflow?tab=readme-ov-file#how-to-use

**Comment by gautamkrishnar** [comment]
Whoops. i think this is a valid issue, thanks for reporting it.

**Comment by gautamkrishnar** [comment]
New version with this change is released: https://github.com/gautamkrishnar/blog-post-workflow/releases/tag/1.8.6
