### ISSUE TITLE
[Bug]: Medium post count status 0 

### ISSUE THREAD

**Issue by iamgagantyagi** [gautamkrishnar/blog-post-workflow#243]
Hi @gautamkrishnar 

I am trying to add a medium blog post source via GitHub workflow but it is showing zero post count 0. Even though my feed URL is showing 1. Below are the details.

![image](https://github.com/gautamkrishnar/blog-post-workflow/assets/40192518/90fc35f1-e4d7-45ed-a5f8-fb5914c98dfc)

![image](https://github.com/gautamkrishnar/blog-post-workflow/assets/40192518/0d4f16d8-a86f-4cfc-9702-bed1bf23223e)

![image](https://github.com/gautamkrishnar/blog-post-workflow/assets/40192518/62eb658b-8190-410d-a1a6-d5c93c733849)

Can you please help me.

**Comment by gautamkrishnar** [comment]
@iamgagantyagi it's because your post do not have any categories. It was an old way to detect medium comments. Looks like it's no longer working. Will remove that for now.

**Comment by gautamkrishnar** [comment]
@iamgagantyagi this is fixed now, thanks for reporting

**Comment by iamgagantyagi** [comment]
Thanks @gautamkrishnar for your quick response. i apricate your help.
