### ISSUE TITLE
[Feature]: Adding the `dummy_commit_message` option for customizing the dummy commit message

### ISSUE THREAD

**Issue by bumb7ebee** [gautamkrishnar/blog-post-workflow#249]
**Is your feature request related to a problem? Please describe.**
No. It might be a good idea to customize the dummy commit message.
Customize the dummy commit message that occurs when the enable_keepalive option is triggered.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### Double check the following
Before creating a feature request, Please make sure that you had done the following, add a checkmark if done by marking it with `[x]`:

- [x] This feature cannot be accomplished using any of the available [options](https://github.com/gautamkrishnar/blog-post-workflow#options) provided by the workflow.
- [x] I had followed all the steps mentioned in the [documentation](https://github.com/gautamkrishnar/blog-post-workflow)

**Comment by gautamkrishnar** [comment]
@bumb7ebee This is a good enhancement, I was planning to migrate this action to keepalive-workflow v2 which removes the use of dummy commits entirely. But this is a good enhancement to have.

**Comment by bumb7ebee** [comment]
> @bumb7ebee This is a good enhancement, I was planning to migrate this action to keepalive-workflow v2 which removes the use of dummy commits entirely. But this is a good enhancement to have.

Thank you!
