### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ritiksoni00** [gautamkrishnar/blog-post-workflow#25]
![Screenshot from 2020-09-07 20-40-30](https://user-images.githubusercontent.com/47344024/92401120-a9fc9c80-f14a-11ea-9bdd-3ab150a2fc83.png)
 what s the problem??

**Comment by gautamkrishnar** [comment]
@ritiksoni00 looks like you are using wrong url, please use `https://medium.com/feed/@rtksoni00` for the `feed_url`
