### ISSUE TITLE
[Bug]: Response 406 when asking for rss stream

### ISSUE THREAD

**Issue by isGeekCode** [gautamkrishnar/blog-post-workflow#250]
**Describe the bug**
I've been using "https://raw.githubusercontent.com/isGeekCode/isGeekCode/main/README.md " on this page and I've been returning 406 for some time now

When I use the provided configuration and the cronjob runs I get a 406 Not Acceptable response in the github action as an error.

To Reproduce

Implement Github Action as described
Let the job run with feed_list: "https://h1guitar.tistory.com/rss"

See the 406 Error
Run gautamkrishnar/blog-post-workflow@master
with:
    feed_list: https://h1guitar.tistory.com/rss
    gh_token: ***
    readme_path: ./README.md
    max_post_count: 5
    disable_sort: false
    filter_comments: stackoverflow/Comment by $author/,stackexchange/Comment by $author/
    template: default
    date_format: UTC:ddd mmm dd yyyy h:MM TT
    user_agent: rss-parser
    accept_header: application/rss+xml
    commit_message: Updated with the latest blog posts
    committer_username: blog-post-bot
    committer_email: blog-post-bot@example.com
    output_only: false
    enable_keepalive: true
    retry_count: 0
    retry_wait_time: 1
    disable_html_encoding: false
    categories_template: default
    disable_item_validation: false
    skip_commit: false
    dummy_commit_message: dummy commit to keep the repository active, see https://git.io/Jtm[4](https://github.com/isGeekCode/isGeekCode/actions/runs/9296896305/job/25587291940#step:3:4)V

Error: https://h1guitar.tistory.com/rss runner failed, please verify the configuration. Error:
##[error]Error: Status code 406

0 blog posts fetched
Expected behavior
I would hav eexpected to read the xml and show the latest blogposts.

Screenshots
None

**Comment by gautamkrishnar** [comment]
@isGeekCode as the message in the console says there is nothing I can do to fix this. 
```
Error: https://h1guitar.tistory.com/rss runner failed, please verify the configuration. Error:
Error: Looks like your website returned 406, There is nothing blog post workflow can do to fix it. Please check your website's RSS feed generation source code. Also double check the URL
```

Read more here: https://github.com/gautamkrishnar/blog-post-workflow?tab=readme-ov-file#faqs-and-common-issues
