### ISSUE TITLE
[Bug]: HTML display 

### ISSUE THREAD

**Issue by kangyans** [gautamkrishnar/blog-post-workflow#254]
### Describe the bug
The display of $B_1^+$ appears to ```B<sub>1</sub><sup>+</sup>```

### Expected behavior
display the correct format, in my example,: $B_1^+$

### Workflow Yml Used
```
 - uses: actions/checkout@v2
 - uses: gautamkrishnar/blog-post-workflow@v1
```

### Double check the following
Before opening a bug, Please make sure that you had done the following, add a checkmark if done by marking it with `[x]`:

- [x] I had gone through the [FAQs](https://github.com/gautamkrishnar/blog-post-workflow#faqs-and-common-issues) 
- [x] I had followed all the steps mentioned in the [documentation](https://github.com/gautamkrishnar/blog-post-workflow)

**Comment by gautamkrishnar** [comment]
@kangyans please use `disable_html_encoding: true`
