### ISSUE TITLE
[Daily-Dev-Bookmarks]: Daily Dev Bookmarks

### ISSUE THREAD

**Issue by NathanielChit** [gautamkrishnar/blog-post-workflow#260]
Source Name: Daily Dev Bookmarks
Source URL: https://api.daily.dev/rss/b/feed
Comments: 
                      
Example:

 
  - [Eddie Jaoude: Authorisation for YOUR apps using an API request with Cerbos](https://app.daily.dev/posts/0cs1k4Fdc?utm_source=rss&amp;utm_medium=bookmarks&amp;utm_campaign=a8USzTm92KKOThBicCr1B)
  - [How to build and Publish A Docker Image 🐳](https://app.daily.dev/posts/SzBWBq3bA?utm_source=rss&amp;utm_medium=bookmarks&amp;utm_campaign=a8USzTm92KKOThBicCr1B)
  -  [Announcing Rustcrab: The Open-Source Hub for Rust Developers](https://app.daily.dev/posts/aUy6oE0Se?utm_source=rss&amp;utm_medium=bookmarks&amp;utm_campaign=a8USzTm92KKOThBicCr1B)
  - [🦀 Simple File Handling in Rust](https://app.daily.dev/posts/7aSnsfaQZ?utm_source=rss&amp;utm_medium=bookmarks&amp;utm_campaign=a8USzTm92KKOThBicCr1B)
  - [The new Rust video is out. By the end of this lesson you will understand the concepts of "Traits" in Rust. When I first heard this word, I had no idea what a "Trait" was, and maybe you have no idea either But it's a concept you may be more familiar with than you think...](https://app.daily.dev/posts/H1Hfyz3Bz?utm_source=rss&amp;utm_medium=bookmarks&amp;utm_campaign=a8USzTm92KKOThBicCr1B)

**Comment by mikeselva123** [comment]
Awesome!! Thanks
