### ISSUE TITLE
[Feature]: Add option to filter by language

### ISSUE THREAD

**Issue by McPringle** [gautamkrishnar/blog-post-workflow#27]
**Is your feature request related to a problem? Please describe.**
My blog supports multiple languages. All blog articles are available in two languages (en+de). This workflow shows all languages in my readme. I would like to filter by language, so only English articles are shown in my readme file.

**Describe the solution you'd like**
A new option "language: en" would be great. As you can see in the following XML code snippet, the blog post (`entry`) has an optional language parameter. If the new option would be set to `en`, only articles with this language should pass the filter.

````
<feed xmlns="http://www.w3.org/2005/Atom">
  ...
  <entry xml:lang="en">
    <title>First Videos of my Bikepacking in Germany 2020</title>
    ...
  </entry>
  ...
</feed>
````

**Describe alternatives you've considered**
I was thinking of creating the feed by language, but actually this is not possible, because I don't host the blog platform myself.

**Additional context**
-

**Comment by gautamkrishnar** [comment]
@McPringle according to the RSS specs the post language should be in `<language></language>` optional channel: https://validator.w3.org/feed/docs/rss2.html, https://www.w3schools.com/xml/rss_tag_language.asp. Filtering via this can be implemented since this is a standard. You might need to update your feed generator code to match this standard.

**Comment by gautamkrishnar** [comment]
@McPringle just gone through the RSS specification. As of now language can be set only on the channel level, there is no spec to set language for the individual **items** (posts) in a single **channel**. So filtering can't be implemented. If your site have multiple language feeds, i recommend you to use different RSS endpoints for different languages. Really sorry for the inconvenience.
