### ISSUE TITLE
Shower some emoji-love!?

### ISSUE THREAD

**Issue by utkarsh2102** [gautamkrishnar/blog-post-workflow#29]
Hi @gautamkrishnar,

Thanks for your work on this!

https://github.com/gautamkrishnar/blog-post-workflow/blob/36be303a1714a740ad6c34dc3bce58a926d4eb2b/blog-post-workflow.js#L253-L259

As I see it, the "Latest Blog Posts" section could you some emoji-love.
What I mean is, maybe we could use some emoji (at random from a pre-defined set) before the blog post. For example:  
1. 💯  `[$title]($url)`
2. 🔥  `[$title]($url)`
3. 💫  `[$title]($url)`
4. 🚀  `[$title]($url)`
5. 🌮  `[$title]($url)`

**Comment by gautamkrishnar** [comment]
Setting a single emoji will be possible via the `template` argument itself. We can introduce a new template variable as `$randomEmoji` for randomizing the emojis. We should use a static array of emojis so that there wont be unwanted commits generated to the people who is running the workflow every hour due to randomizatiion.

**Comment by utkarsh2102** [comment]
Aye, you're right!
It's best if we use [💯, 🔥, 💫, 🚀, 🌮] in that order to avoid a ton of unnecessary commits!

Thanks, again, for your work on this! ❤️

**Comment by gautamkrishnar** [comment]
Got some more ideas for this, we don't have to hard code emojis:

- `$randomEmoji` key can be parametrized, users can use `$randomEmoji(💯, 🔥, 💫, 🚀, 🌮)` in their template if they want to randomly generate posts based on the emojis they had given.
- `$emojiKey` key can be used to show emojis in the order he/she has specified. `$emojiKey(💯, 🔥, 💫) title` will give them posts like:
         - 💯 title1
         - 🔥 title2
         -  💫 title3
         - 💯 title4
         - 🔥 title5

**Comment by gautamkrishnar** [comment]
@utkarsh2102 this is released on version  [1.2.8](https://github.com/gautamkrishnar/blog-post-workflow/releases/tag/1.2.8), you can now use it. Thanks a lot for the suggestion.

**Comment by LukePrior** [comment]
It could be a good addition to allow emoji selection based on the post category.

**Comment by gautamkrishnar** [comment]
@LukePrior for now i am not planning to inegrate that in the workflow. You can easily acheive that by using the following code:

```YAML
name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"
          item_exec: |
                if (post.categories.includes("category-name")) {
                    post.title = "😃  " + post.title;
                |

**Comment by LukePrior** [comment]
> @LukePrior for now i am not planning to inegrate that in the workflow. You can easily acheive that by using the following code:
> 
> ```yaml
> name: Latest blog post workflow
> on:
>   schedule: # Run workflow automatically
>     - cron: '0 * * * *' # Runs every hour, on the hour
>   workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
> 
> jobs:
>   update-readme-with-blog:
>     name: Update this repo's README with latest blog posts
>     runs-on: ubuntu-latest
>     steps:
>       - name: Checkout
>         uses: actions/checkout@v2
>       - name: Pull in dev.to posts
>         uses: gautamkrishnar/blog-post-workflow@master
>         with:
>           feed_list: "https://dev.to/feed/gautamkrishnar,https://www.gautamkrishnar.com/feed/"
>           item_exec: |
>                 if (post.categories.includes("category-name")) {
>                     post.title = "😃  " + post.title;
>                 |
> ```

Hi, thanks for this code.

I am trying it out but I seem to be running into an issue.

My Action:

```yaml
jobs:
  update-readme-with-blog:
    name: Update README blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://lukeprior.github.io/blog/feed"
          item_exec: |
            if (post.categories.includes("SondeHub")) { post.title = "🎈  " + post.title; }
```

My feed:

https://lukeprior.github.io/blog/feed

My logs:

![image](https://user-images.githubusercontent.com/22492406/170695358-a5e447b7-2d68-4021-a8cf-c4ca8fdf938c.png)

Result:

![image](https://user-images.githubusercontent.com/22492406/170695398-940abacc-78e0-450f-9f6a-d9b0c0122a8e.png)

Expected result:

![image](https://user-images.githubusercontent.com/22492406/170695486-fc8baf13-37e0-4c59-9d6a-890efaccf526.png)

I was just wondering if you could spot any obvious errors as to why this might not be working?

**Comment by gautamkrishnar** [comment]
@LukePrior categories arreay is empty from your feed. 
![Screenshot 2022-05-27 at 8 39 57 PM](https://user-images.githubusercontent.com/8397274/170727651-4c5ca461-9c6e-442e-90b6-de99421ed313.png)

Your feed should have `<category>SondeHub</category>` for this to work, see: https://github.com/gautamkrishnar/blog-post-workflow/issues/105#issue-1045286882. You currently have `<category term="SondeHub"/>` which is not a [RSS standard](https://validator.w3.org/feed/docs/rss2.html#syndic8) way of representing category.

**Comment by Qiamast** [comment]
i make this template :)
`template: "$newline - $randomEmoji(💯,🔥,💫,🚀,🌮)[$title]($url) $newline - $description $newline"`
