### ISSUE TITLE
Add more popular sources

### ISSUE THREAD

**Issue by gautamkrishnar** [gautamkrishnar/blog-post-workflow#31]
See the list of sources documented at https://github.com/gautamkrishnar/blog-post-workflow#popular-sources

Add more RSS Feed sources to the list.

**Comment by jpacsai** [comment]
Hi, I have a good one to add if that's okay :)

**Comment by hexxdump** [comment]
can I work on this ?

**Comment by gautamkrishnar** [comment]
yes @hexxdump

**Comment by hexxdump** [comment]
will it be possible to add 'hacktoberfest' topic to your repository?

**Comment by gautamkrishnar** [comment]
@hexxdump done

**Comment by Red-0111** [comment]
@gautamkrishnar Please will try my best

**Comment by gautamkrishnar** [comment]
@Red-0111 you can start adding one. No need to assign it since this ticket is for multiple people to implement.

**Comment by Curious-Yu** [comment]
I would like to add a new source

**Comment by gautamkrishnar** [comment]
Thanks, @Curious-Yu just left a comment on your PR.

**Comment by mdsanima** [comment]
Hi, @gautamkrishnar this shuld be work on `.rst` file instead of `.md`? Please let me know! Thank you. Anyway, great tools. Keep coding!

**Comment by gautamkrishnar** [comment]
@mdsanima why do you think we need a rst file?

**Comment by Vyvy-vi** [comment]
Hey um I had a query...
Can this take data from gists too?

**Comment by gautamkrishnar** [comment]
Only if it supports RSS format Vyvy-vi

**Comment by Vyvy-vi** [comment]
sadly gists don't :/
Though love the action ❤️

**Comment by gautamkrishnar** [comment]
Thanks @Vyvy-vi 😃

**Comment by kaustubhgupta** [comment]
Hi @gautamkrishnar,
I have a suggestion to include Analytics India Magazine, a leading Data Science and technology website where many authors write articles related to machine learning and other tech stacks. The feed link is working perfectly fine for me:
```
https://analyticsindiamag.com/author/{author_name}/feed/
```

I have included this in my workflow too: [my workflow](https://github.com/kaustubhgupta/kaustubhgupta/blob/master/.github/workflows/blog-post-workflow.yml)

**Comment by gautamkrishnar** [comment]
@kaustubhgupta feel free to add that via a PR

**Comment by adrianpaniagualeon** [comment]
Added Tumblr 
#56

**Comment by vikichand** [comment]
Did anyone think of adding LinkedIn? 🤔

**Comment by gautamkrishnar** [comment]
@vikichand it is possible but not straignt forward since linkedin donthave an rss feed. You can do that with services like zapier.

**Comment by gautamkrishnar** [comment]
@vikichand just checked zapier, they also stopped supporting linkdin. So the only option is writing your own rss generator using the linkedin api.

**Comment by gautamkrishnar** [comment]
Closing this issue since we already have enough sources now. Feel free to add any new one via pull requests.

**Comment by gautamkrishnar** [comment]
@vikichand you can try using this for linkedin posts: https://automate.io/integration/linkedin/rss-feed Please let me knoe if it is working.
