### ISSUE TITLE
[Feature]: Remove newlines from RSS post titles

### ISSUE THREAD

**Issue by nil0x42** [gautamkrishnar/blog-post-workflow#34]
**Is your feature request related to a problem? Please describe.**
I use a twitter RSS feed as input, and sometimes titles containg newlines, leading to improper markdown formatting.

**Describe the solution you'd like**
Replace occurences of `\r\n` & `\n` in the title by simple space

**Describe alternatives you've considered**
n/a

**Additional context**
Here's how titles get formatted:
![Screenshot_2020-10-10_13-22-26](https://user-images.githubusercontent.com/3504393/95656132-c0a46380-0afb-11eb-9679-c22baa06e54e.png)
![Screenshot_2020-10-10_13-21-04](https://user-images.githubusercontent.com/3504393/95656135-c26e2700-0afb-11eb-9aa6-0be1e880b39f.png)

**Comment by gautamkrishnar** [comment]
Working on this.

**Comment by gautamkrishnar** [comment]
Released on https://github.com/gautamkrishnar/blog-post-workflow/releases/tag/1.3.1

**Comment by nil0x42** [comment]
Wow ! I'm simply shocked by your reactivity !

**Comment by nil0x42** [comment]
Just for the record. There is a problem with `\n` & `\r` literals in `item_exec`, so they must be escaped.

As an example, for my case, the correct `item_exec` is:
```yml
item_exec: "post.title = post.title.replace(/(?:\\r\\n|\\r|\\n)/g,' ');"
```

**Comment by gautamkrishnar** [comment]
Thanks for pointing it out @nil0x42

**Comment by nil0x42** [comment]
@gautamkrishnar , is it possible to use this new feature to ignore an entry?
Let's say I want to have 5 first entries that do not contain a specific string in title, is it possible with item_exec to just ignore entry?

**Comment by gautamkrishnar** [comment]
@nil0x42 thanks for the suggestion, just released this feature. You can ignore any item by setting it to **null** via javascript using the `item_exec` param.

Eg:
```javascript
item_exec: "if (post.title.indexOf('example title prefix') === -1) { post = null; }"
```
You may need to add proper escaping for some special characters.

**Comment by nil0x42** [comment]
Hi ! Thank you again for the speed at which you adress issues !
I tried and it doesn't work because `post` is const, so i get ` TypeError: Assignment to constant variable.` error.

Also, as item_exec migh alter title's length, it might be useful to put TITLE_MAX_LENGTH trimming block code after item_exec, so if item_exec changes the title-'s length, the trimming happens after.

**Comment by gautamkrishnar** [comment]
@nil0x42 oopsie, I will fix that, will update the code to use let instead. 👍  Happy to help.

**Comment by gautamkrishnar** [comment]
@nil0x42 thanks for your suggestions, it's now released: https://github.com/gautamkrishnar/blog-post-workflow/releases/tag/1.3.4
