### ISSUE TITLE
[Feature]: Add an option to set title max-length 

### ISSUE THREAD

**Issue by nil0x42** [gautamkrishnar/blog-post-workflow#35]
**Is your feature request related to a problem? Please describe.**
Some RSS sources (such as twitter) may include too long post titles.

**Describe the solution you'd like**
Adding an option to set a max-length to post titles would be a cool feature

**Describe alternatives you've considered**
When title has to be truncated, a triple-dot can be added to the end of string to make clear the title has been truncated

**Additional context**
RSS from last tweets (formatted by rss.app) have very long titles:
![Screenshot_2020-10-10_13-22-26](https://user-images.githubusercontent.com/3504393/95656226-5cce6a80-0afc-11eb-9887-6eae9f395acb.png)

**Comment by gautamkrishnar** [comment]
This is released on https://github.com/gautamkrishnar/blog-post-workflow/releases/tag/1.3.0
