### ISSUE TITLE
[Bug]: Not detecting posts

### ISSUE THREAD

**Issue by Edstub207** [gautamkrishnar/blog-post-workflow#37]
For some reason this workflow isn't working for me and I'm not sure why...

Logs and RSS Feed: 
![image](https://user-images.githubusercontent.com/13305475/97236613-5a972c00-17dd-11eb-909c-b5c8afe1ff0e.png)

README.MD 
![image](https://user-images.githubusercontent.com/13305475/97236658-76023700-17dd-11eb-9b59-0cc2e11c14ac.png)

**Comment by gautamkrishnar** [comment]
@Edstub207 looks like your content is encoded, you need to have a plain text version of the feed to show it via the blog post workflow.

Example:
https://github.com/gautamkrishnar/blog-post-workflow/blob/e672f4debedb5f70e5742834d99e1425e58fbf89/test/sample.xml#L9-L33

In your case the title and description is in cdata, not as plain text. Please follow the correct RSS spec to make it work.

**Comment by gautamkrishnar** [comment]
Oops its using medium, let me check why it's not working. It was working earlier as #2

**Comment by gautamkrishnar** [comment]
@Edstub207 it is due to the medium filter. Please use to fix it:

```
filter_comments: ""
```

**Comment by gautamkrishnar** [comment]
As of now, since there is no way to filter out the medium comments other than checking it for **undefined** category closing this for now. Will add a warning in the doc.

**Comment by Edstub207** [comment]
That fixed it, thank you!
