### ISSUE TITLE
[Feature]: Can Support Feed List is the github issues by github api

### ISSUE THREAD

**Issue by doit** [gautamkrishnar/blog-post-workflow#55]
**Is your feature request related to a problem? Please describe.**
sometimes， someone use the github issues as a blog.  Is the feed url a github repo issue?

**Describe the solution you'd like**
 The feed url is a github repo issue, like https://github.com/jiangtao/blog/issues?q=is%3Aopen+is%3Aissue

**Comment by gautamkrishnar** [comment]
Hi @doit right now github dont supports outputing issues are RSS format but you can write your own wrapper on top of github api to generate it. Adding that this project would be beyond the scope of this project.

**Comment by doit** [comment]
> Hi @doit right now github dont supports outputing issues are RSS format but you can write your own wrapper on top of github api to generate it. Adding that to this project would be beyond the scope of this project.

Got it
