### ISSUE TITLE
[Feature]:  Having a template file and an output file

### ISSUE THREAD

**Issue by fundor333** [gautamkrishnar/blog-post-workflow#58]
**Is your feature request related to a problem? Please describe.**

A lot of time, when I am working on the README.md of my profile I make change on my machine and, when I try to push, I have conflict to resolve for the blog section.

**Describe the solution you'd like**

I like to have an config for input path (like readme_path) and a output path.

If you have a input and output path you can have a TEMPLATE.md for input (with an empty  section) and a README.md where the section for the blog is fill with what you want.

**Comment by gautamkrishnar** [comment]
@fundor333 can you please elaborare what you are suggestiung with a minimal example of 

- Contents of TEMPLATE.md
- Contents of README.md
- Contents of README.md after the blog post workflow is ran.

**Comment by fundor333** [comment]
This is my idea. You have a template clean like this If the config is set. It allways remain in this state. It's an input

## TEMPLATE.md

~~~
### Hi there

- 🔭 I’m currently working on something 
- 🔭 I’m currently working on something 
- 🔭 I’m currently working on something 

<!-- BLOG-POST-LIST:START -->
<!-- BLOG-POST-LIST:END -->

![forthebadge](https://forthebadge.com/images/badges/you-didnt-ask-for-this.svg)
![forthebadge](https://forthebadge.com/images/badges/powered-by-electricity.svg)
![forthebadge](https://forthebadge.com/images/badges/you-didnt-ask-for-this.svg)
![forthebadge](https://forthebadge.com/images/badges/powered-by-electricity.svg)
~~~

README is the output of the workflow.

## README.md  before the blog post workflow is ran

~~~
### Hi there

- 🔭 I’m currently working on something 
- 🔭 I’m currently working on something 
- 🔭 I’m currently working on something 

<!-- BLOG-POST-LIST:START -->
* OLD POST
* OLD POST
* OLD POST
<!-- BLOG-POST-LIST:END -->

![forthebadge](https://forthebadge.com/images/badges/you-didnt-ask-for-this.svg)
![forthebadge](https://forthebadge.com/images/badges/powered-by-electricity.svg)
![forthebadge](https://forthebadge.com/images/badges/you-didnt-ask-for-this.svg)
![forthebadge](https://forthebadge.com/images/badges/powered-by-electricity.svg)
~~~

## README.md  after the blog post workflow is ran

~~~
### Hi there

- 🔭 I’m currently working on something 
- 🔭 I’m currently working on something 
- 🔭 I’m currently working on something 

<!-- BLOG-POST-LIST:START -->
* NEW POST
* NEW POST
* NEW POST
<!-- BLOG-POST-LIST:END -->

![forthebadge](https://forthebadge.com/images/badges/you-didnt-ask-for-this.svg)
![forthebadge](https://forthebadge.com/images/badges/powered-by-electricity.svg)
![forthebadge](https://forthebadge.com/images/badges/you-didnt-ask-for-this.svg)
![forthebadge](https://forthebadge.com/images/badges/powered-by-electricity.svg)
~~~

If you have a complex README or a long one you can edit without having conflict or without "spam" if you have a long output  for blog-post-workflow

**Comment by gautamkrishnar** [comment]
@fundor333 In my opinion, this will add additional confusion to the users. Even if you add this template thing the readme will be committed with the changes. Lets me explain with an example:

- You had 3 blog posts on your blog, following is the state of your readme:
```
<!-- BLOG-POST-LIST:START -->
* OLD POST
* OLD POST
* OLD POST
<!-- BLOG-POST-LIST:END -->

# Skills
- Java
````
- You cloned the above project to your local by running:
```
git clone https://github.com/fundor333/fundor333.git
```
- Now you have the local clone that is synced with the upstream.
- Lets say you published a new blog post on your site
- Reame workflow ran and the following is the change that is made by the workflow:
```

**Comment by gautamkrishnar** [comment]
`

**Comment by gautamkrishnar** [comment]
@fundor333 In my opinion, this will add additional confusion to the users. Even if you add this template thing the readme will be committed with the changes. Lets me explain with an example:

- You had 3 blog posts on your blog, following is the state of your readme:
```
<!-- BLOG-POST-LIST:START -->
* OLD POST
* OLD POST
* OLD POST
<!-- BLOG-POST-LIST:END -->

# Skills
- Java
````
- You cloned the above project to your local by running:
```
git clone https://github.com/fundor333/fundor333.git
```
- Now you have the local clone that is synced with the upstream.
- Lets say you published a new blog post on your site
- blog workflow ran and the following is the change that is made by the workflow:
```
<!-- BLOG-POST-LIST:START -->
* NEW POST
* OLD POST
* OLD POST
<!-- BLOG-POST-LIST:END -->

# Skills
- Java
```
- Your locally cloned repo dont have this change it will still have:
```
<!-- BLOG-POST-LIST:START -->
* OLD POST
* OLD POST
* OLD POST
<!-- BLOG-POST-LIST:END -->

# Skills
- Java
````
- Lets say you updated your local clone with new skill and committed it:
```
<!-- BLOG-POST-LIST:START -->
* OLD POST
* OLD POST
* OLD POST
<!-- BLOG-POST-LIST:END -->

# Skills
- Java
- CPP
````
- Now if you try to push it, you may have conflicts.

Its unecessary to implement this feature, please it is a standard git workflow to take the puil and fxing conflicts before committing.

**Comment by gautamkrishnar** [comment]
also this workflow will update the readme only if you wrote a blog post while you did the local change of the code, it is too unlikely to happen in the most cases. Readme will not be updated all the time when this workflow is run, it will update only if there is a change in the RSS feed.

**Comment by gautamkrishnar** [comment]
The changes made by the workflow will be also extremely minimal, i dont think that there is a problem in fixing the merge conflicts if you follow the correct git workflow.
Eg: https://github.com/ayushi7rawat/ayushi7rawat/commit/5f650894554254a192413bd0d41e27d17b121664
