### ISSUE TITLE
[Bug]: Run git pull

### ISSUE THREAD

**Issue by Milo123459** [gautamkrishnar/blog-post-workflow#59]
sometimes the ref pulling fails, before running git push do git pull to fix this

thanks

**Comment by gautamkrishnar** [comment]
@Milo123459 this is already done in this workflow: https://github.com/gautamkrishnar/blog-post-workflow/blob/master/blog-post-workflow.js#L326

If you are experincing problems while running paralell with other workflows. please adjust the timing of the cron job for this workflow workflow.
