### ISSUE TITLE
Feed sort

### ISSUE THREAD

**Issue by cowbe0x004** [gautamkrishnar/blog-post-workflow#7]
I'd like to make a feature request, sorry if this is the wrong place.

I'm using the workflow to pull youtube playlists feeds, and the feed is being sorted by the video date. It'd be great if we can choose to sort by when the video was added to the playlist, or sort randomly. Thank you.

**Comment by gautamkrishnar** [comment]
@cowbe0x004 sorry it will not be possible since those data is not available in the XML URL: https://www.youtube.com/feeds/videos.xml?playlist_id=PLJNqgDLpd5E69Kc664st4j7727sbzyx0X also the feed-parser don't support it.

**Comment by cowbe0x004** [comment]
Thank you. I'm not very good at reading js, but I see there's this code,

```
// Sorting posts based on date
  postsArray.sort(function (a, b) {
    return b.date - a.date;
  });
```
If we omit that, would the order appear as they are in the feed?

**Comment by gautamkrishnar** [comment]
@cowbe0x004 that is doable, will reopen and implement. We can disable sorting entirely with a flag,

**Comment by gautamkrishnar** [comment]
@cowbe0x004 just released this: https://github.com/gautamkrishnar/blog-post-workflow/releases/tag/1.0.6, please set `disable_sort` to `true`

**Comment by cowbe0x004** [comment]
That works, thank you for the quick turn around!
