### ISSUE TITLE
[Feature]: Add WordPress sites in README

### ISSUE THREAD

**Issue by infinity-plus** [gautamkrishnar/blog-post-workflow#70]
**Is your feature request related to a problem? Please describe.**
WordPress Blogs are more common nowadays, many people including me use it for blogging. It will be great to let people know that this workflow can fetch blogs from WordPress as well.

**Describe the solution you'd like**
It is more of a tip, just add `/feed/` to your  WordPress URL. For example, if my website is example.com, this Workflow can fetch the latest blogs from https://example.com/feed/

Example: [My Workflow File](https://github.com/infinity-plus/infinity-plus/blob/141da907d4d307623de13fc9e0adfc43f7de6ded/.github/workflows/blog-post-workflow.yml#L16)

Result:
[![image](https://user-images.githubusercontent.com/39484407/122881048-574a4500-d358-11eb-955d-88cd1c3ae9de.png)](https://github.com/infinity-plus/infinity-plus#blog-posts)

**Comment by gautamkrishnar** [comment]
@infinity-plus Thanks for openning the issue, wordpress is already there in the popular sources list: https://github.com/gautamkrishnar/blog-post-workflow#popular-sources

**Comment by infinity-plus** [comment]
My bad, sorry
