### ISSUE TITLE
Requires a bit more explanation 

### ISSUE THREAD

**Issue by DuncanFaulkner** [gautamkrishnar/blog-post-workflow#75]
Hi,
Saw your article and thought I would try this out on my readme page.

I could not get this to work with my credentials in the actions file. Having tried your actions file with my feed it worked.

you need to include extra files to it get to work. You need the blog-post-workflow.js file in a dist directory and the action.yml file in the root for it to actually work. This took me several hours (way too long) to get this to work.

please update your readme with the additional files required to run this, otherwise great job :+1: 

Many thanks

**Comment by gautamkrishnar** [comment]
@DuncanFaulkner this workflow's source codes is not meant to be used that way. You can just include the workflow in your own Github action. You really don't have to copy paste the source code to your own repository. Please check the readme for more information.

https://github.com/gautamkrishnar/blog-post-workflow/blob/master/README.md

You can also check out the following video for a demo on how to use it: https://www.youtube.com/watch?v=ECuqb5Tv9qI

**Comment by DuncanFaulkner** [comment]
OK the video did make it clear that I need to include - ```uses: gautamkrishnar/blog-post-workflow@master``` I was changing this line to be my org/repo@master that isn't clear until you watch the video.

**Comment by gautamkrishnar** [comment]
@DuncanFaulkner In readme you can see the following, i am only mentioning about updating the feed url, nothing else https://github.com/gautamkrishnar/blog-post-workflow#:~:text=Replace%20the%20above%20url%20list%20with%20your%20own%20rss%20feed%20urls.%20See%20popular-sources%20for%20a%20list%20of%20common%20RSS%20feed%20urls.: 
<img width="946" alt="Screenshot 2021-07-22 at 2 34 27 AM" src="https://user-images.githubusercontent.com/8397274/126559909-b96c6444-4520-44b3-bbd1-3eb00d48ad60.png">

**Comment by DuncanFaulkner** [comment]
Yes sorry, I completely overthought this, when reading it back the steps are quite clear again my appologises.
Great work by the way :+1:

**Comment by gautamkrishnar** [comment]
@DuncanFaulkner  No problem, thanks a lot for using it. Really happy to know that you liked it 😄.
