### ISSUE TITLE
Add option to specify commit message

### ISSUE THREAD

**Issue by UtkarshVerma** [gautamkrishnar/blog-post-workflow#8]
It would be neat to let users specify a custom commit message since everyone has their own way of writing commit messages.

**Comment by gautamkrishnar** [comment]
@UtkarshVerma thanks for reporting this. WIll work on it.

**Comment by UtkarshVerma** [comment]
Thanks for the quick implementation. Much appreciated.

**Comment by gautamkrishnar** [comment]
@UtkarshVerma please test this on the latest version and let me know if you experience any problems: https://github.com/gautamkrishnar/blog-post-workflow#options
