### ISSUE TITLE
[New Source]: Blogger

### ISSUE THREAD

**Issue by flyingsonu122** [gautamkrishnar/blog-post-workflow#99]
Source Name: Blogger
Source URL:  https://www.blogger.com/feeds/{blogID}/posts/default

OR

https://{blog-name}.blogspot.com/feeds/posts/default

Example: https://www.blogger.com/feeds/1650914765603013759/posts/default

OR

https://singlebucks.blogspot.com/feeds/posts/default

**Comment by gautamkrishnar** [comment]
Thanks for the suggestion @kaustubhgupta 😄
